-- Drop Tables
DROP TABLE flight_crew CASCADE CONSTRAINTS;
DROP TABLE ticket CASCADE CONSTRAINTS;
DROP TABLE flight CASCADE CONSTRAINTS;
DROP TABLE airport CASCADE CONSTRAINTS;
DROP TABLE plane CASCADE CONSTRAINTS;
DROP TABLE crew CASCADE CONSTRAINTS;
DROP TABLE passenger CASCADE CONSTRAINTS;

-- Drop sequence
DROP SEQUENCE crew_crew_id_seq;

-- Create passenger table
CREATE TABLE passenger(
    passenger_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(45) NOT NULL,
    last_name VARCHAR2(45) NOT NULL,
    CONSTRAINT passenger_passenger_id_pk PRIMARY KEY (passenger_id)
);


-- Create crew table
CREATE TABLE crew (
    crew_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(45) NOT NULL,
    last_name VARCHAR2(45) NOT NULL,
    title VARCHAR2(45) NOT NULL,
    CONSTRAINT crew_crew_id_pk PRIMARY KEY (crew_id)
);

-- Create the sequence for crew
CREATE SEQUENCE crew_crew_id_seq 
INCREMENT BY 5 
START WITH 15;

-- Create plane table
CREATE TABLE plane(
    plane_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    make VARCHAR2(45) NOT NULL,
    plane_model VARCHAR2(45) NOT NULL,
    capacity NUMBER(3),
    CONSTRAINT plane_plane_id_pk PRIMARY KEY (plane_id)
);

-- Create airport table
CREATE TABLE airport (
    airport_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    airport_name VARCHAR2(45) NOT NULL,
    street VARCHAR2(45) NOT NULL,
    city VARCHAR2(45) NOT NULL,
    zipcode VARCHAR2(45) NOT NULL,
    state VARCHAR2(45) NOT NULL,
    country VARCHAR2(45) NOT NULL,
    CONSTRAINT airport_airport_id_pk PRIMARY KEY (airport_id)
);

-- Create flight table
CREATE TABLE flight (
    flight_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    arrival_time DATE NOT NULL,
    departure_time DATE NOT NULL,
    gate VARCHAR2(5) NOT NULL,
    arrival_airport_id NUMBER NOT NULL,
    departure_airport_id NUMBER NOT NULL,
    plane_id NUMBER NOT NULL,
    CONSTRAINT flight_flight_id_pk PRIMARY KEY (flight_id),
    CONSTRAINT flight_arrival_airport_fk FOREIGN KEY (arrival_airport_id) REFERENCES airport(airport_id),
    CONSTRAINT flight_departure_airport_fk FOREIGN KEY (departure_airport_id) REFERENCES airport(airport_id),
    CONSTRAINT flight_plane_fk FOREIGN KEY (plane_id) REFERENCES plane(plane_id)
);

-- Create ticket table
CREATE TABLE ticket (
    ticket_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    passenger_id NUMBER NOT NULL,
    flight_id NUMBER NOT NULL,
    boarding_time DATE,
    boarding_group VARCHAR2(5),
    has_upgraded_seating CHAR(1),
    has_disability_seating CHAR(1),
    CONSTRAINT ticket_ticket_id_pk PRIMARY KEY (ticket_id),
    CONSTRAINT ticket_passenger_fk FOREIGN KEY (passenger_id) REFERENCES passenger(passenger_id),
    CONSTRAINT ticket_flight_fk FOREIGN KEY (flight_id) REFERENCES flight(flight_id),
    CONSTRAINT ticket_upgrade_chk CHECK (has_upgraded_seating IN ('Y','N')),
    CONSTRAINT ticket_disability_chk CHECK (has_disability_seating IN ('Y','N')));

-- Create flight_crew table
CREATE TABLE flight_crew (
    flight_id NUMBER NOT NULL,
    crew_id NUMBER NOT NULL,
    role_on_flight VARCHAR2(45) NOT NULL,
    CONSTRAINT flight_crew_pk PRIMARY KEY (flight_id, crew_id),
    CONSTRAINT flight_crew_flight_fk FOREIGN KEY (flight_id) REFERENCES flight(flight_id),
    CONSTRAINT flight_crew_crew_fk FOREIGN KEY (crew_id) REFERENCES crew(crew_id)
);


-- DATA FOR PASSENGER
INSERT INTO passenger(passenger_id, first_name, last_name)
    VALUES(1, 'Justin', 'Smith');
INSERT INTO passenger(passenger_id, first_name, last_name)
    VALUES(2, 'Olivia', 'Carter');
INSERT INTO passenger(passenger_id, first_name, last_name)
    VALUES(3, 'Mason', 'Rivera');
INSERT INTO passenger(passenger_id, first_name, last_name)
    VALUES(4, 'Sophia', 'Bennett');
INSERT INTO passenger(passenger_id, first_name, last_name)
    VALUES(5, 'Liam', 'Patel');
INSERT INTO passenger(passenger_id, first_name, last_name)
    VALUES(6, 'Ethan', 'Coleman');
INSERT INTO passenger(passenger_id, first_name, last_name)
    VALUES(7, 'Samuel', 'Wright');
INSERT INTO passenger(passenger_id, first_name, last_name)
    VALUES(8, 'Jacob', 'Morales');
INSERT INTO passenger(passenger_id, first_name, last_name)
    VALUES(9, 'Mitch', 'Hamilton');
INSERT INTO passenger(passenger_id, first_name, last_name)
    VALUES(10, 'Aria', 'Johnson');
INSERT INTO passenger(passenger_id, first_name, last_name)
    VALUES(11, 'Benjamin', 'Foster');
INSERT INTO passenger(passenger_id, first_name, last_name)
    VALUES(12, 'Noah', 'Brooks');
    
-- DATA FOR CREW
INSERT INTO crew(crew_id, first_name, last_name, title)
    VALUES(crew_crew_id_seq.NEXTVAL, 'Charlie', 'Wilson', 'Flight Attendant');
INSERT INTO crew(crew_id, first_name, last_name, title)
    VALUES(crew_crew_id_seq.NEXTVAL, 'Edison', 'Parker', 'Flight Attendant');
INSERT INTO crew(crew_id, first_name, last_name, title)
    VALUES(crew_crew_id_seq.NEXTVAL, 'Natalie', 'Pierce', 'Flight Attendant');
INSERT INTO crew(crew_id, first_name, last_name, title)
    VALUES(crew_crew_id_seq.NEXTVAL, 'Charlie', 'Wilson', 'Pilot');
INSERT INTO crew(crew_id, first_name, last_name, title)
    VALUES(crew_crew_id_seq.NEXTVAL, 'Jordan', 'McAllister', 'Pilot');
INSERT INTO crew(crew_id, first_name, last_name, title)
    VALUES(crew_crew_id_seq.NEXTVAL, 'Elena', 'Vasquez', 'Pilot');
INSERT INTO crew(crew_id, first_name, last_name, title)
    VALUES(crew_crew_id_seq.NEXTVAL, 'Damien', 'Clarke', 'Pilot');
INSERT INTO crew(crew_id, first_name, last_name, title)
    VALUES(crew_crew_id_seq.NEXTVAL, 'Julian', 'Mercer', 'Pilot');
INSERT INTO crew(crew_id, first_name, last_name, title)
    VALUES(crew_crew_id_seq.NEXTVAL, 'Kendra', 'Holloway', 'Pilot');
INSERT INTO crew(crew_id, first_name, last_name, title)
    VALUES(crew_crew_id_seq.NEXTVAL, 'Mariah', 'Monroe', 'Pilot');
INSERT INTO crew(crew_id, first_name, last_name, title)
    VALUES(crew_crew_id_seq.NEXTVAL, 'Lillian', 'Cho', 'Pilot');
    
-- DATA FOR PLANE
INSERT INTO plane(plane_id, make, plane_model, capacity)
    VALUES(1, 'Boeing', '747‑400', 100);
INSERT INTO plane(plane_id, make, plane_model, capacity)
    VALUES(2, 'Boeing', '757‑200', 50);
INSERT INTO plane(plane_id, make, plane_model, capacity)
    VALUES(3, 'Boeing', '767‑300ER', 160);
INSERT INTO plane(plane_id, make, plane_model)
    VALUES(4, 'Airbus', 'A330‑300');
INSERT INTO plane(plane_id, make, plane_model, capacity)
    VALUES(5, 'Airbus', 'A380‑900', 350);
INSERT INTO plane(plane_id, make, plane_model)
    VALUES(6, 'Airbus', 'A380‑800');
INSERT INTO plane(plane_id, make, plane_model, capacity)
    VALUES(7, 'Embraer', 'E170', 70);
INSERT INTO plane(plane_id, make, plane_model, capacity)
    VALUES(8, 'Embraer', 'E175', 80);
INSERT INTO plane(plane_id, make, plane_model)
    VALUES(9, 'Embraer', 'E190');
    
-- DATA FOR AIRPORT
INSERT INTO airport(airport_id, airport_name, street, city, zipcode, state, country)
    VALUES(1, 'Hartsfield-Jax Atlanta International Airport', '6000 N Terminal Pkwy', 'Atlanta', '30320', 'Georgia', 'USA');
INSERT INTO airport(airport_id, airport_name, street, city, zipcode, state, country)
    VALUES(2, 'Los Angeles International Airport', '1 World Way', 'Los Angeles', '90045', 'California', 'USA');
INSERT INTO airport(airport_id, airport_name, street, city, zipcode, state, country)
    VALUES(3, 'Chicago O Hare International Airport', '10000 W O''Hare Ave', 'Chicago', '60666', 'Illinois', 'USA');
INSERT INTO airport(airport_id, airport_name, street, city, zipcode, state, country)
    VALUES(4, 'Dallas/Fort Worth International Airport', '2400 Aviation Dr', 'Dallas', '75261', 'Texas', 'USA');
INSERT INTO airport(airport_id, airport_name, street, city, zipcode, state, country)
    VALUES(5, 'Denver International Airport', '8500 Peña Blvd', 'Denver', '80249', 'Colorado', 'USA');
INSERT INTO airport(airport_id, airport_name, street, city, zipcode, state, country)
    VALUES(6, 'Miami International Airport', '2100 NW 42nd Ave', 'Miami', '33142', 'Florida', 'USA');
INSERT INTO airport(airport_id, airport_name, street, city, zipcode, state, country)
    VALUES(7, 'Seattle-Tacoma International Airport', '17801 International Blvd', 'Seattle', '98158', 'Washington', 'USA');
INSERT INTO airport(airport_id, airport_name, street, city, zipcode, state, country)
    VALUES(8, 'John F. Kennedy International Airport', 'JFK Access Rd', 'New York', '11430', 'New York', 'USA');

-- DATA FOR FLIGHT
INSERT INTO flight (arrival_time, departure_time, gate, arrival_airport_id, departure_airport_id, plane_id)
    VALUES (TO_DATE('03/15/2026 14:30','MM/DD/YYYY HH24:MI'),
            TO_DATE('03/15/2026 12:00','MM/DD/YYYY HH24:MI'),
            'A1', 2, 1, 1);
INSERT INTO flight (arrival_time, departure_time, gate, arrival_airport_id, departure_airport_id, plane_id)
    VALUES (TO_DATE('03/16/2026 18:45','MM/DD/YYYY HH24:MI'),
            TO_DATE('03/16/2026 15:30','MM/DD/YYYY HH24:MI'),
            'B4', 3, 2, 2);
INSERT INTO flight (arrival_time, departure_time, gate, arrival_airport_id, departure_airport_id, plane_id)
    VALUES (TO_DATE('03/17/2026 09:20','MM/DD/YYYY HH24:MI'),
            TO_DATE('03/17/2026 06:00','MM/DD/YYYY HH24:MI'),
            'C2', 4, 1, 3);
INSERT INTO flight (arrival_time, departure_time, gate, arrival_airport_id, departure_airport_id, plane_id)
    VALUES (TO_DATE('03/18/2026 22:10','MM/DD/YYYY HH24:MI'),
            TO_DATE('03/18/2026 19:30','MM/DD/YYYY HH24:MI'),
            'D7', 5, 3, 4);
INSERT INTO flight (arrival_time, departure_time, gate, arrival_airport_id, departure_airport_id, plane_id)
    VALUES (TO_DATE('03/19/2026 11:00','MM/DD/YYYY HH24:MI'),
            TO_DATE('03/19/2026 08:15','MM/DD/YYYY HH24:MI'),
            'E3', 6, 4, 5);
INSERT INTO flight (arrival_time, departure_time, gate, arrival_airport_id, departure_airport_id, plane_id)
    VALUES (TO_DATE('03/20/2026 16:40','MM/DD/YYYY HH24:MI'),
            TO_DATE('03/20/2026 13:25','MM/DD/YYYY HH24:MI'),
            'F6', 7, 5, 6);
INSERT INTO flight (arrival_time, departure_time, gate, arrival_airport_id, departure_airport_id, plane_id)
    VALUES (TO_DATE('03/21/2026 07:55','MM/DD/YYYY HH24:MI'),
            TO_DATE('03/21/2026 05:30','MM/DD/YYYY HH24:MI'),
            'G9', 8, 6, 7);
INSERT INTO flight (arrival_time, departure_time, gate, arrival_airport_id, departure_airport_id, plane_id)
    VALUES (TO_DATE('03/22/2026 20:30','MM/DD/YYYY HH24:MI'),
            TO_DATE('03/22/2026 17:10','MM/DD/YYYY HH24:MI'),
            'H1', 1, 7, 8);
INSERT INTO flight (arrival_time, departure_time, gate, arrival_airport_id, departure_airport_id, plane_id)
    VALUES (TO_DATE('03/23/2026 15:15','MM/DD/YYYY HH24:MI'),
            TO_DATE('03/23/2026 12:45','MM/DD/YYYY HH24:MI'),
            'A5', 2, 8, 2);
INSERT INTO flight (arrival_time, departure_time, gate, arrival_airport_id, departure_airport_id, plane_id)
    VALUES (TO_DATE('03/24/2026 19:00','MM/DD/YYYY HH24:MI'),
            TO_DATE('03/24/2026 16:20','MM/DD/YYYY HH24:MI'),
            'B8', 3, 1, 3);

-- DATA FOR TICKET
INSERT INTO ticket VALUES (DEFAULT, 1, 1, TO_DATE('03/15/2026 11:20','MM/DD/YYYY HH24:MI'), 'A', 'Y', 'N');
INSERT INTO ticket VALUES (DEFAULT, 2, 1, TO_DATE('03/15/2026 11:25','MM/DD/YYYY HH24:MI'), 'B', 'N', 'N');
INSERT INTO ticket VALUES (DEFAULT, 3, 2, TO_DATE('03/16/2026 14:50','MM/DD/YYYY HH24:MI'), 'A', 'Y', 'N');
INSERT INTO ticket VALUES (DEFAULT, 4, 3, TO_DATE('03/17/2026 05:15','MM/DD/YYYY HH24:MI'), 'C', 'N', 'Y');
INSERT INTO ticket VALUES (DEFAULT, 5, 4, TO_DATE('03/18/2026 18:45','MM/DD/YYYY HH24:MI'), 'B', 'N', 'N');
INSERT INTO ticket VALUES (DEFAULT, 6, 5, TO_DATE('03/19/2026 07:30','MM/DD/YYYY HH24:MI'), 'A', 'Y', 'N');
INSERT INTO ticket VALUES (DEFAULT, 7, 6, TO_DATE('03/20/2026 12:40','MM/DD/YYYY HH24:MI'), 'C', 'N', 'N');
INSERT INTO ticket VALUES (DEFAULT, 8, 7, TO_DATE('03/21/2026 04:45','MM/DD/YYYY HH24:MI'), 'B', 'N', 'N');
INSERT INTO ticket VALUES (DEFAULT, 9, 8, TO_DATE('03/22/2026 16:20','MM/DD/YYYY HH24:MI'), 'A', 'Y', 'N');
INSERT INTO ticket VALUES (DEFAULT, 10, 9, TO_DATE('03/23/2026 12:00','MM/DD/YYYY HH24:MI'), 'C', 'N', 'Y');
INSERT INTO ticket VALUES (DEFAULT, 11, 10, TO_DATE('03/24/2026 15:35','MM/DD/YYYY HH24:MI'), 'B', 'N', 'N');
INSERT INTO ticket VALUES (DEFAULT, 12, 3, TO_DATE('03/17/2026 05:10','MM/DD/YYYY HH24:MI'), 'A', 'Y', 'N');

-- DATA FOR FLIGHT CREW
INSERT INTO flight_crew VALUES (1, 15, 'Pilot');
INSERT INTO flight_crew VALUES (1, 20, 'Co-Pilot');
INSERT INTO flight_crew VALUES (1, 25, 'Flight Attendant');
INSERT INTO flight_crew VALUES (2, 30, 'Pilot');
INSERT INTO flight_crew VALUES (2, 35, 'Flight Attendant');
INSERT INTO flight_crew VALUES (3, 15, 'Pilot');
INSERT INTO flight_crew VALUES (3, 40, 'Flight Attendant');
INSERT INTO flight_crew VALUES (4, 45, 'Pilot');
INSERT INTO flight_crew VALUES (4, 50, 'Co-Pilot');
INSERT INTO flight_crew VALUES (5, 55, 'Pilot');
INSERT INTO flight_crew VALUES (6, 60, 'Pilot');

COMMIT;