-- Drop tables for multiple runs
DROP TABLE flight_crew CASCADE CONSTRAINTS;
DROP TABLE ticket CASCADE CONSTRAINTS;
DROP TABLE flight CASCADE CONSTRAINTS;
DROP TABLE airport CASCADE CONSTRAINTS;
DROP TABLE plane CASCADE CONSTRAINTS;
DROP TABLE crew CASCADE CONSTRAINTS;
DROP TABLE passenger CASCADE CONSTRAINTS;

-- Create passenger table
CREATE TABLE passenger(
    passenger_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(45) NOT NULL,
    last_name VARCHAR2(45) NOT NULL,
    CONSTRAINT passenger_passenger_id_pk PRIMARY KEY (passenger_id)
);

-- Create crew table
CREATE TABLE crew (
    crew_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(45) NOT NULL,
    last_name VARCHAR2(45) NOT NULL,
    title VARCHAR2(45) NOT NULL,
    CONSTRAINT crew_crew_id_pk PRIMARY KEY (crew_id)
);

-- Create Sequence for crew table
CREATE SEQUENCE crew_crew_id_seq 
INCREMENT BY 5 
START WITH 100;

-- Create plane table
CREATE TABLE plane(
    plane_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    make VARCHAR2(45) NOT NULL,
    plane_model VARCHAR2(45) NOT NULL,
    capacity NUMBER(3),
    CONSTRAINT plane_plane_id_pk PRIMARY KEY (plane_id)
);

-- Create airport table
CREATE TABLE airport (
    airport_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    airport_name VARCHAR2(45) NOT NULL,
    street VARCHAR2(45) NOT NULL,
    city VARCHAR2(45) NOT NULL,
    state VARCHAR2(45) NOT NULL,
    country VARCHAR2(45) NOT NULL,
    CONSTRAINT airport_airport_id_pk PRIMARY KEY (airport_id)
);

-- Create flight table
CREATE TABLE flight (
    flight_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    arrival_time DATE NOT NULL,
    departure_time DATE NOT NULL,
    gate_number VARCHAR2(5) NOT NULL,
    arrival_airport_id NUMBER NOT NULL,
    departure_airport_id NUMBER NOT NULL,
    plane_id NUMBER NOT NULL,
    CONSTRAINT flight_flight_id_pk PRIMARY KEY (flight_id),
    CONSTRAINT flight_arrival_airport_fk FOREIGN KEY (arrival_airport_id) REFERENCES airport(airport_id),
    CONSTRAINT flight_departure_airport_fk FOREIGN KEY (departure_airport_id) REFERENCES airport(airport_id),
    CONSTRAINT flight_plane_fk FOREIGN KEY (plane_id) REFERENCES plane(plane_id)
);

-- Create ticket table
CREATE TABLE ticket (
    ticket_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    passenger_id NUMBER NOT NULL,
    flight_id NUMBER NOT NULL,
    boarding_time DATE,
    boarding_group VARCHAR2(5),
    has_upgraded_seating CHAR(1),
    has_disability_seating CHAR(1),
    CONSTRAINT ticket_ticket_id_pk PRIMARY KEY (ticket_id),
    CONSTRAINT ticket_passenger_fk FOREIGN KEY (passenger_id) REFERENCES passenger(passenger_id),
    CONSTRAINT ticket_flight_fk FOREIGN KEY (flight_id) REFERENCES flight(flight_id),
    CONSTRAINT ticket_upgrade_chk CHECK (has_upgraded_seating IN ('Y','N')),
    CONSTRAINT ticket_disability_chk CHECK (has_disability_seating IN ('Y','N')));

-- Create flight_crew table
CREATE TABLE flight_crew (
    flight_id NUMBER NOT NULL,
    crew_id NUMBER NOT NULL,
    role_on_flight VARCHAR2(45) NOT NULL,
    CONSTRAINT flight_crew_pk PRIMARY KEY (flight_id, crew_id),
    CONSTRAINT flight_crew_flight_fk FOREIGN KEY (flight_id) REFERENCES flight(flight_id),
    CONSTRAINT flight_crew_crew_fk FOREIGN KEY (crew_id) REFERENCES crew(crew_id)
);

COMMIT;